---
- name: Configure VMs with alex user and SSH key
  hosts: all
  become: yes
  tasks:
    - name: Create alex user
      user:
        name: alex
        state: present
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes

    - name: Add SSH public key
      authorized_key:
        user: alex
        state: present
        key: #put your PC's ssh key here

    - name: Check passwordless sudo #cowboy
      lineinfile:
        path: /etc/sudoers.d/alex
        state: present
        create: yes
        mode: '0440'
        line: 'alex ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Change hostname
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
